server:
  port: 8081

spring:
  application:
    name: weather-service
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

mock:
  weather:
    enabled: false

api:
  openweather:
    key: ${OPENWEATHER_API_KEY:}

logging:
  level:
    com.weather: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
