server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084/realms/weather-event
          jwk-set-uri: http://keycloak:8080/realms/weather-event/protocol/openid-connect/certs
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: weather-service
          uri: lb://weather-service
          predicates:
            - Path=/api/weather/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**
        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/api/recommendations/**
        - id: agenda-service
          uri: lb://agenda-service
          predicates:
            - Path=/api/agenda/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**,/api/admin/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
